# Generated by Django 4.0.5 on 2022-08-08 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tt', '0002_student'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
    ]
