# Generated by Django 4.1 on 2022-08-13 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt', '0003_alter_student_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day', models.CharField(max_length=500)),
                ('course1', models.CharField(max_length=500)),
                ('course2', models.CharField(max_length=500)),
                ('course3', models.CharField(max_length=500)),
                ('course4', models.CharField(max_length=500)),
                ('course5', models.CharField(max_length=500)),
                ('course6', models.CharField(max_length=500)),
                ('course7', models.CharField(max_length=500)),
                ('course8', models.CharField(max_length=500)),
                ('course9', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'timetable',
            },
        ),
    ]
