# Generated by Django 4.1 on 2022-08-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt', '0004_timetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor_subject',
            name='credits',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='student',
            name='std_id',
            field=models.CharField(max_length=500, primary_key=True, serialize=False),
        ),
    ]
